hiragana = [
    {
        name: 'a',
        char: '',
        sound: 'ah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'i',
        char: '',
        sound: 'ee',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'u',
        char: '',
        sound: 'ooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'e',
        char: '',
        sound: 'eh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'o',
        char: '',
        sound: 'oh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ka',
        char: '',
        sound: 'kah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ki',
        char: '',
        sound: 'kee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ku',
        char: '',
        sound: 'kooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ke',
        char: '',
        sound: 'keh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ko',
        char: '',
        sound: 'koh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'sa',
        char: '',
        sound: 'sah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'shi',
        char: '',
        sound: 'she',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'su',
        char: '',
        sound: 'ooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'se',
        char: '',
        sound: 'seh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'so',
        char: '',
        sound: 'soh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ta',
        char: '',
        sound: 'tah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'chi',
        char: '',
        sound: 'chee',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'tsu',
        char: '',
        sound: 'Tsuu',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'te',
        char: '',
        sound: 'teh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'to',
        char: '',
        sound: 'toh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'na',
        char: '',
        sound: 'nah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ni',
        char: '',
        sound: 'nee',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'nu',
        char: '',
        sound: 'nooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ne',
        char: '',
        sound: 'neh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'no',
        char: '',
        sound: 'noh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ha',
        char: '',
        sound: 'hah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'hi',
        char: '',
        sound: 'hee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'hu',
        char: '',
        sound: 'hfooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'he',
        char: '',
        sound: 'heh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ho',
        char: '',
        sound: 'hoh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ma',
        char: '',
        sound: 'mah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'mi',
        char: '',
        sound: 'mee',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'mu',
        char: '',
        sound: 'mooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'me',
        char: '',
        sound: 'meh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'mo',
        char: '',
        sound: 'moh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ra',
        char: '',
        sound: 'rah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ri',
        char: '',
        sound: 'ree',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'ru',
        char: '',
        sound: 'rooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 're',
        char: '',
        sound: 'reh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ro',
        char: '',
        sound: 'roh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ya',
        char: '',
        sound: 'yah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'yu',
        char: '',
        sound: 'you',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'yo',
        char: '',
        sound: 'oh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'n',
        char: '',
        sound: 'ng',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'wa',
        char: '',
        sound: 'wa',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'wo',
        char: '',
        sound: 'oh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'pa',
        char: '',
        sound: 'pah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'pi',
        char: '',
        sound: 'pee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'pu',
        char: '',
        sound: 'pooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'pe',
        char: '',
        sound: 'peh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'po',
        char: '',
        sound: 'poh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ba',
        char: '',
        sound: 'bah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'bi',
        char: '',
        sound: 'bee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'bu',
        char: '',
        sound: 'booh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'be',
        char: '',
        sound: 'beh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'bo',
        char: '',
        sound: 'boh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'da',
        char: '',
        sound: 'dah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'di',
        char: '',
        sound: 'dee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'du',
        char: '',
        sound: 'dooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'de',
        char: '',
        sound: 'deh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'do',
        char: '',
        sound: 'doh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'za',
        char: '',
        sound: 'zah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'zi',
        char: '',
        sound: 'zee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'zu',
        char: '',
        sound: 'zooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ze',
        char: '',
        sound: 'zeh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'zo',
        char: '',
        sound: 'zoh',
        imgSrc: '',
        soundSrc: '',
    },
]