const hiragana = [
    {
        name: 'a',
        char: 'あ',
        sound: 'ah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'i',
        char: 'い',
        sound: 'ee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'u',
        char: 'う',
        sound: 'ooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'e',
        char: 'え',
        sound: 'eh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'o',
        char: 'お',
        sound: 'oh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ka',
        char: 'か',
        sound: 'kah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ki',
        char: 'き',
        sound: 'kee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ku',
        char: 'く',
        sound: 'kooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ke',
        char: 'け',
        sound: 'keh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ko',
        char: 'こ',
        sound: 'koh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'sa',
        char: 'さ',
        sound: 'sah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'shi',
        char: 'し',
        sound: 'she',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'su',
        char: 'す',
        sound: 'ooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'se',
        char: 'せ',
        sound: 'seh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'so',
        char: 'そ',
        sound: 'soh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ta',
        char: 'た',
        sound: 'tah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'chi',
        char: 'ち',
        sound: 'chee',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'tsu',
        char: 'つ',
        sound: 'Tsuu',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'te',
        char: 'て',
        sound: 'teh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'to',
        char: 'と',
        sound: 'toh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'na',
        char: 'な',
        sound: 'nah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ni',
        char: 'に',
        sound: 'nee',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'nu',
        char: 'ぬ',
        sound: 'nooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ne',
        char: 'ね',
        sound: 'neh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'no',
        char: 'の',
        sound: 'noh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ha',
        char: 'は',
        sound: 'hah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'hi',
        char: 'ひ',
        sound: 'hee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'hu',
        char: 'ふ',
        sound: 'hfooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'he',
        char: 'へ',
        sound: 'heh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ho',
        char: 'ほ',
        sound: 'hoh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ma',
        char: 'ま',
        sound: 'mah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'mi',
        char: 'み',
        sound: 'mee',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'mu',
        char: 'む',
        sound: 'mooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'me',
        char: 'め',
        sound: 'meh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'mo',
        char: 'も',
        sound: 'moh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ra',
        char: 'ら',
        sound: 'rah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ri',
        char: 'り',
        sound: 'ree',
        imgSrc: '',
        soundSrc: '',
    },    {
        name: 'ru',
        char: 'る',
        sound: 'rooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 're',
        char: 'れ',
        sound: 'reh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ro',
        char: 'ろ',
        sound: 'roh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ya',
        char: 'や',
        sound: 'yah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'yu',
        char: 'ゆ',
        sound: 'you',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'yo',
        char: 'よ',
        sound: 'oh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'nn',
        char: 'ん',
        sound: 'ng',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'wa',
        char: 'わ',
        sound: 'wa',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'wo',
        char: 'を',
        sound: 'oh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'pa',
        char: 'ぱ',
        sound: 'pah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'pi',
        char: 'ぴ',
        sound: 'pee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'pu',
        char: 'ぷ',
        sound: 'pooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'pe',
        char: 'ぺ',
        sound: 'peh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'po',
        char: 'ぽ',
        sound: 'poh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ba',
        char: 'ば',
        sound: 'bah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'bi',
        char: 'び',
        sound: 'bee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'bu',
        char: 'ぶ',
        sound: 'booh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'be',
        char: 'べ',
        sound: 'beh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'bo',
        char: 'ぼ',
        sound: 'boh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'da',
        char: 'だ',
        sound: 'dah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'di',
        char: 'ぢ',
        sound: 'dee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'du',
        char: 'づ',
        sound: 'dooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'de',
        char: 'で',
        sound: 'deh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'do',
        char: 'ど',
        sound: 'doh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'za',
        char: 'ざ',
        sound: 'zah',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'zi',
        char: 'じ',
        sound: 'zee',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'zu',
        char: 'ず',
        sound: 'zooh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'ze',
        char: 'ぜ',
        sound: 'zeh',
        imgSrc: '',
        soundSrc: '',
    },
    {
        name: 'zo',
        char: 'ぞ',
        sound: 'zoh',
        imgSrc: '',
        soundSrc: '',
    },
]

export { hiragana };